import type { Metadata } from 'next'
import './globals.css'
import { fontBody } from './fonts'
import { Header } from '@/components/header/header'
import { cookies } from 'next/headers'

export const metadata: Metadata = {
  title: 'Gym',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const token = cookies().get('token')?.value
  return (
    <html
      lang="pt-br"
      className={`bg-zinc-200 scroll-smooth antialiased ${fontBody.className}`}
    >
      <body>
        {token && <Header />}
        <div className="max-w-[1200px] mx-auto antialiased">{children}</div>
      </body>
    </html>
  )
}
