import type { Metadata } from 'next'
import './globals.css'
import { roboto } from './fonts'

export const metadata: Metadata = {
  title: 'Gym',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
